### ISSUE TITLE
Add torch to conda environment

### ISSUE THREAD

**Issue by bensworth** [Multilevel-NN/torchbraid#4]
Hi guys, I'm installing torchbraid on a cluster. I'm trying to keep my python version in separate conda environments. Do you guys have suggestions on how to properly include the torch path in a conda environment? The standard PYTHONPATH approach didn't work, I think because conda python doesn't use the python path. I also tried the conda develop approach, which is supposed to take the place of setup.py files and make some sort of symlink, but this also didn't work. The Make seemed succesful, but if I run make tests I get `ModuleNotFoundError: No module named 'torch'.` Same if I just try to import torch in Python.

**Comment by eric-c-cyr** [comment]
Hmm, let me check what I did on my cluster. I've been struggling with these things recently (even reporting it up through mangment). But I have made some progress, so lets see what I can help with.

**Comment by eric-c-cyr** [comment]
A few questions come to mind: 

1. If you do `which python` does this correspond to the desired python?
2. You said earlier that you can import torch?
3. Can you share your makefile.inc?

For my linux cluster I'm building with

```
MPIRUN=mpirun
PYTHON=python

# For my Linux
#####################################
XBRAID_ROOT=/home/eccyr/Packages/xbraid/braid
POSTFIX=cpython-37m-x86_64-linux-gnu.so
CC=mpicc
LDSHARED=mpicc -shared
EXTRA_FLAGS=-O3 -fPIC
```

As far as I can test the POSTFIX is pretty flaky, and may need to change depending on what you actually build. 
My PYTHONPATH includes
```
/home/eccyr/Packages/torchbraid/torchbraid:/home/eccyr/Packages/torchbraid
```

**Comment by bienz2** [comment]
Hey Ben,

If it’s helpful I just installed this on one of our clusters at UNM with only using Conda environments and added the steps to a file:

# 1. unload any mpi and python modules
# 2. conda create --name braid_env cpython openmpi-mpicc mpi4py pytorch
conda activate braid_env
# 4. cd /users/bienz/xbraid
# 5. make clean
# 6. make debug=no braid
# 7. cd /users/bienz/torchbraid
# 8. python3-config --extension-suffix
# 9. vi makefile.inc
#        MPIRUN=mpirun
#        PYTHON=python3
#        # For my Linux
#        #####################################
#        XBRAID_ROOT=/users/bienz/xbraid/braid
#        POSTFIX=cpython-37m-x86_64-linux-gnu.so
#        CC=mpicc
#        LDSHARED=mpicc -shared
#        EXTRA_FLAGS=-O3 -fPIC
# 10. make
# 11. export TORCHBRAID_DIR=/users/bienz/torchbraid
# 12. export PYTHONPATH=${TORCHBRAID_DIR}/torchbraid:${TORCHBRAID_DIR}:${PYTHONPATH}
# 13. make tests
# 14. make tests-serial

The PYTHONPATH environment variable worked for me and all the tests passed fine.  Not sure if you have a different issue on your cluster, but just wanted to include the steps that worked for me in case they help.  My student was running into similar errors to what you are, and it seems like it was due to not including openmpi-mpicc in the Conda environment installation line and having conflicting modules loaded.

Amanda

On Jun 21, 2021, at 2:13 PM, Eric C. Cyr ***@***.******@***.***>> wrote:

  [EXTERNAL]


A few questions come to mind:

  1.  If you do which python does this correspond to the desired python?
  2.  You said earlier that you can import torch?
  3.  Can you share your makefile.inc?

For my linux cluster I'm building with

MPIRUN=mpirun
PYTHON=python

# For my Linux
#####################################
XBRAID_ROOT=/home/eccyr/Packages/xbraid/braid
POSTFIX=cpython-37m-x86_64-linux-gnu.so
CC=mpicc
LDSHARED=mpicc -shared
EXTRA_FLAGS=-O3 -fPIC


As far as I can test the POSTFIX is pretty flaky, and may need to change depending on what you actually build.
My PYTHONPATH includes

/home/eccyr/Packages/torchbraid/torchbraid:/home/eccyr/Packages/torchbraid

**Comment by bensworth** [comment]
Also, for what it's worth, I tried using MPICH from the cluster and installing via Conda. There I make it to make tests, then do not recognize `MPI_Gather`, which is definitely not good
```
Traceback (most recent call last):
  File "/vast/home/southworth/python_libs/torchbraid/tests/test_callbacks.py", line 37, in <module>
    import torchbraid
  File "/home/southworth/python_libs/torchbraid/torchbraid/__init__.py", line 32, in <module>
    from .layer_parallel import LayerParallel
  File "/home/southworth/python_libs/torchbraid/torchbraid/layer_parallel.py", line 44, in <module>
    import torchbraid.odenet_apps as apps
  File "/home/southworth/python_libs/torchbraid/torchbraid/odenet_apps.py", line 35, in <module>
    from torchbraid_app import BraidApp
ImportError: /home/southworth/python_libs/torchbraid/torchbraid/torchbraid_app.cpython-39-x86_64-linux-gnu.so: undefined symbol: MPI_Gather
```
Oddly enough, I have the same mpirun problem using OpenMPI on C-code on the cluster, even if I use the module available on the cluster. Posted on issue on OpenMPI Github to see if they know what's going on.
