### ISSUE TITLE
local_steps v. global_steps in ParallelNet for MNIST

### ISSUE THREAD

**Issue by jbschroder** [Multilevel-NN/torchbraid#7]
Hi Eric @eric-c-cyr 

In the examples/mnist/utils.py, I may have run across a bug.  Take a look at the below screenshot.  I keep running into errors using some combinations of multiple processors and nsteps that I think should work.

![Screen Shot 2022-04-01 at 2 00 34 PM](https://user-images.githubusercontent.com/4768739/161333451-3df4f39d-58e8-4a58-92ef-b39002679ddd.png)

**Comment by eric-c-cyr** [comment]
This is something I changed recently. (I thought I sent an email to you about it, but its not showing up in my inbox. So that might be a my intention not making it to my action) I recently switched to it being global steps as a result of trying to do the multiple NODE case. In that case you end up describing the whole network and then different things are distributed.

**Comment by jbschroder** [comment]
Thanks!  Do you think we should switch it to being global steps in general?

**Comment by eric-c-cyr** [comment]
It should be global steps in general at this point. I've propoagated through all the code. Though its possible I missed a variable.

**Comment by eric-c-cyr** [comment]
@jbschroder did you work through this?

**Comment by jbschroder** [comment]
This was fixed in  5c372b04a91be77eedf6a86add936e7aff30060d

**Comment by jbschroder** [comment]
Yes, I did.  THank you for double checking!  I just closed the ticket.
